### ISSUE TITLE
Just a question but I couldn't find you email

### ISSUE THREAD

**Issue by albu77** [mamezou-tech/electron-example-browserview#1]
I can't understand where the ['resize'] in  ['resize'].forEach is coming from.
If you have time to expalin I will be glad.

**Comment by kondoumh** [comment]
This code is equivalent to:

```javascript
  mainWindow.on('resize', e => {
    // do something
  });
```

I copied this code from another project of mine.The original code was written using forEach as below to assign the same function to the `move` event besides `resize`.

```javascript
  ['resize', 'move'].forEach(e => {
    mainWindow.on(e, () => {
      // do something
    });
  });
```

When I pasted the code into this sample, I removed the unnecessary `move` events, resulting in confusing code like your question.

**Comment by albu77** [comment]
Thanks for the answer; is there any doc explaining the equivalent with `mainWindow.on(`

**Comment by albu77** [comment]
Forget it I understand, the array is used for the different names of event you want to do something with.....
