### ISSUE TITLE
start the app

### ISSUE THREAD

**Issue by Minyar2004** [mamezou-tech/electron-example-browserview#2]
Hi,

The app does not work for me, I have this : 

![Capture](https://user-images.githubusercontent.com/29538843/228263174-bb5bd553-d4bc-4e16-8178-3fd676e4f39a.PNG)

Nothing happens when pressing the two buttons "elecronjs.org" and "local.html"

Can you help me to make it work

thanks

**Comment by kondoumh** [comment]
Thank you for your report. I had the same issue when running on Windows 10. After resizing the window, the content was displayed. I'll look it up.

**Comment by Minyar2004** [comment]
Thank you for your reply, it actually works by resizing the window...

**Comment by kondoumh** [comment]
@Devhercule
Fixed on #3
